name: Keep Render Backend Alive

on:
  schedule:
    # Runs every half an hour
    - cron: '*/30 * * * *'
  workflow_dispatch: # manual trigger

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend with retry
        env:
          BACKEND_URL: ${{ secrets.RENDER_BACKEND_URL }}
        run: |
          MAX_RETRIES=2
          for i in $(seq 1 $MAX_RETRIES); do
            RESPONSE=$(curl -s --max-time 120 -o /dev/null -w "%{http_code}" "$BACKEND_URL")
            if [ "$RESPONSE" -ge 200 ] && [ "$RESPONSE" -lt 400 ]; then
              echo "Backend is awake (HTTP $RESPONSE)"
              exit 0
            else
              echo "Ping failed (HTTP $RESPONSE), retrying in 10s..."
              sleep 10
            fi
          done
          echo "All retries failed. Backend did not respond."
          exit 1
